### ISSUE TITLE
Connection test odoo-woocommerce connector failure

### ISSUE THREAD

**Issue by maria2233** [techreceptives/connector-woocommerce#2]
Installation error.
Connection fails.  "Enter valid Url"

**Comment by mgielissen** [comment]
Verify that Wordpress Permalinks is /%postname% for accessing WooCommerce API /wc-api/

**Comment by mcassuto** [comment]
@mgielissen : you should add an helper in the field to avoid this sort of error...
I did the same one ....

**Comment by parthivgls** [comment]
This is in general done in order to have clean url, as standard practice in wordpress. But good idea.. we'll include it in documentation as well.

**Comment by maria2233** [comment]
Yes wordpress permalinks did it. Thank you. SOLVED.
