### ISSUE TITLE
Product Syncronization

### ISSUE THREAD

**Issue by ch-aurich** [techreceptives/connector-woocommerce#4]
Hi,

I have an existing odoo installation that has all my products. 
Aditionally I have a new installation of woocommerce. There I started to insert my products.

Now I would like to add your connector to syncronize the products between the two installations. What I notice is that all products that I have in the shop are added as new products in odoo regardless if they already exist or not. Is there a way to manually or automatically sync the exsisting products?

Kind regards
Christian

**Comment by parthivgls** [comment]
with some scripted efforts possible to map existing products. Not possible in current connector out of box.
