### ISSUE TITLE
Does this module use the Woo API 

### ISSUE THREAD

**Issue by mcassuto** [techreceptives/connector-woocommerce#6]
2 of the previous bugs ssem to be solved by changin the Wordpresse permlinks configuration.

The point is Woo has a wonderful API very well documented... Are you using it ?
http://woothemes.github.io/woocommerce-rest-api-docs

**Comment by parthivgls** [comment]
@mcassuto : Yes we do use that, but this APIs are not so efficient and not having all the functions that we need for efficient sync. so to over come that limitation we have made an additional module which adds missing web services. Module is here : https://wordpress.org/plugins/connector-woo-odoo/
